name: CI
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  hardhat-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'
      - name: Install packages
        run: npm i
      - name: Create dummy .env from .env.example
        run: mv .env.example .env
      - name: Compile contracts
        run: npm run compile
      - name: Run Tests
        run: CI=true npm test

  foundry-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1.7.0
      - name: Install dependencies
        run: forge install
      - name: Run Foundry tests
        run: forge test -vvv
        env:
          FOUNDRY_INVARIANT_RUNS: 256
          FOUNDRY_INVARIANT_DEPTH: 50
